name = "emily_zola_theme"
description = "a KISS theme for Zola"
license = "MIT"
homepage = "https://gitlab.com/kyoheiu/emily_zola_theme"
demo = "https://emily-zola-theme.netlify.app/"

[extra]
# Author name, appears in footer.
emily_author = "author name"

# Path to the header icon / favicon image.
# Please save image to static/images
emily_icon = "/images/logo.png"

emily_favicon = "/images/favicon.png"

# header icon width.
# height will be automatically rendered.
emily_iconsize = 70

# top text in index.html.
emily_words = "Keep it simple and stupid."

# number of posts in index.html.
emily_indexposts = 5

# switch to dark-theme
emily_dark_mode = false

[author]
name = "Kyohei Uto"
homepage = "https://gitlab.com/kyoheiu"
